const stations: {
  [key: string]: { [key: string]: number | number[] }
} = {
  "Aljunied": {"EW": 9},
  "Bartley": {"CC": 12, "CE": 12},
  "Bayfront": {"CE": 3},
  "Bedok": {"EW": 5},
  "Bishan": {"CC": 15, "CE": 15},
  "Boon Lay": {"EW": 27},
  "Botanic Gardens": {"CC": 19, "CE": 19},
  "Bras Basah": {"CC": 2},
  "Bugis": {"EW": 12},
  "Buona Vista": {"EW": 21, "CC": 22, "CE": 22},
  "Caldecott": {"CC": 17, "CE": 17},
  "Cantonment": {"CC": 31, "CE": 31},
  "Chinese Garden": {"EW": 25},
  "City Hall": {"EW": 13},
  "Clementi": {"EW": 23},
  "Commonwealth": {"EW": 20},
  "Dakota": {"CC": 8, "CE": 8},
  "Dhoby Ghaut": {"CC": 1},
  "Dover": {"EW": 22},
  "Esplanade": {"CC": 3},
  "Eunos": {"EW": 7},
  "Farrer Road": {"CC": 20, "CE": 20},
  "Gul Circle": {"EW": 30},
  "HarbourFront": {"CC": 29, "CE": 29},
  "Haw Par Villa": {"CC": 25, "CE": 25},
  "Holland Village": {"CC": 21, "CE": 21},
  "Joo Koon": {"EW": 29},
  "Jurong East": {"EW": 24},
  "Kallang": {"EW": 10},
  "Kembangan": {"EW": 6},
  "Kent Ridge": {"CC": 24, "CE": 24},
  "Keppel": {"CC": 30, "CE": 30},
  "Labrador Park": {"CC": 27, "CE": 27},
  "Lakeside": {"EW": 26},
  "Lavender": {"EW": 11},
  "Lorong Chuan": {"CC": 14, "CE": 14},
  "MacPherson": {"CC": 10, "CE": 10},
  "Marina Bay": {"CE": [2,33], "CC": 33},
  "Marymount": {"CC": 16, "CE": 16},
  "Mountbatten": {"CC": 7, "CE": 7},
  "Nicoll Highway": {"CC": 5, "CE": 5},
  "one-north": {"CC": 23, "CE": 23},
  "Outram Park": {"EW": 16},
  "Pasir Panjang": {"CC": 26, "CE": 26},
  "Pasir Ris": {"EW": 1},
  "Paya Lebar": {"EW": 8, "CC": 9, "CE": 9},
  "Pioneer": {"EW": 28},
  "Prince Edward Road": {"CC": 32, "CE": 32},
  "Promenade": {"CC": 4, "CE": 4},
  "Queenstown": {"EW": 19},
  "Raffles Place": {"EW": 14},
  "Redhill": {"EW": 18},
  "Serangoon": {"CC": 13, "CE": 13},
  "Simei": {"EW": 3},
  "Stadium": {"CC": 6, "CE": 6},
  "Tai Seng": {"CC": 11, "CE": 11},
  "Tampines": {"EW": 2},
  "Tanah Merah": {"EW": 4, "CG": 0},
  "Tanjong Pagar": {"EW": 15},
  "Telok Blangah": {"CC": 28, "CE": 28},
  "Tiong Bahru": {"EW": 17},
  "Tuas Crescent": {"EW": 31},
  "Tuas Link": {"EW": 33},
  "Tuas West Road": {"EW": 32},
  "Changi Airport": {"CG": 2},
  "Expo": {"CG": 1},
}

export default stations;
