export const enum ActionTypes {
  FETCH_STATION_DATA = 'FETCH_STATION_DATA',
  FETCH_STATION_DATA_FULFILLED = 'FETCH_STATION_DATA_FULFILLED',
  FETCH_STATION_DATA_REJECTED = 'FETCH_STATION_DATA_REJECTED',
  GET_METRO_ROUTES = 'GET_METRO_ROUTES',
  UPDATE_STATION = 'UPDATE_STATION',
}
